apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamie
  labels:
    app: streamie
spec:
  selector:
    matchLabels:
      app: streamie
  replicas: 1
  # strategy:
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app: streamie
        # octopusexport: OctopusExport
    spec:
      containers:
        - name: streamie
          image: "ghcr.io/narze/streamie/streamie:bvxpcia"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: TWITCH_OAUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: streamie
                  key: TWITCH_OAUTH_TOKEN
            - name: OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: streamie
                  key: OAUTH_CLIENT_ID
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: streamie
                  key: DISCORD_TOKEN
            - name: DEV_GUILD_ID
              valueFrom:
                secretKeyRef:
                  name: streamie
                  key: DEV_GUILD_ID
            - name: PORT
              value: "3000"
